[package]
name = "gankshell"
version = "0.1.0"
edition = "2021"

description = "Uma shell"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rustyline = "9.0"
chrono = "0.4"
whoami = "1.2"